
-- Find total customers by countries
SELECT * FROM gold.dim_customers

SELECT
	country,
	Count(DISTINCT customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC


-- Find total customers by gender
 SELECT
	gender,
	COUNT(DISTINCT customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by catagory

SELECT * FROM gold.dim_products

SELECT 
	category,
	COUNT(DISTINCT product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average cost in each category?

SELECT * FROM gold.fact_sales 
	
SELECT
	category,
	 AVG(cost) AS average_cost
FROM gold.dim_products 
GROUP BY category
ORDER BY average_cost DESC

-- What is the total revenue generated for each category?
SELECT 
	dp.category,
	SUM(fs.sales_amount) AS total_revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products dp ON dp.product_key = fs.product_key
GROUP BY dp.category
ORDER BY total_revenue


-- Find total revenue is generated by each customer

SELECT 
	dc.customer_key,
	dc.first_name,
	dc.last_name,
	SUM(sales_amount) AS total_revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc ON dc.customer_key = fs.customer_key
GROUP BY dc.customer_key, dc.first_name, dc.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold items across counties?

SELECT 
	dc.country,
	SUM(fs.quantity) AS total_sold_items
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc ON dc.customer_key = fs.customer_key
GROUP BY dc.country
ORDER BY total_sold_items DESC

